### ISSUE TITLE
Ok to store basemap files for antique, flat blue, midnight in this repo?

### ISSUE THREAD

**Issue by makella** [CartoDB/basemap-styles#7]
Hey @jaakla 

Besides Voyager, Positron, and Dark Matter, we also have a few other CARTO basemaps available in Builder like Antique, Flat Blue, and World Midnight Commander.

These basemaps live in a specific CARTO account.

@javitonino and I were talking today about a place where we could put the assets for the maps (image markers, pattern fills) as well as copies of the .carto files to have as backup.

Since we have this repo with all of our other basemap-related items, I thought this would be a good place to store those files as well.

Would that be ok? 

cc @javitonino

**Comment by jaakla** [comment]
I think the .carto files would be quite big, as they have also map content, so putting them to github directly might not work technically. If you can somehow split it to components - leave data out and version/save cartocss and small assets, then this would fit github well, but then we need some specific tooling to "extract" carto files and then "compile" them back together. If you don't plan much active development with them, then github probably does not give much value, and just storing .carto files in some suitable file storage (S3?) might be much simpler.

Note that this repo is public, check the IP before adding them here. We have another private repo for private styles.

**Comment by javitonino** [comment]
I mean the metadata-only `.carto` files, of course, which is just a big zipped json, should be a few kbs each. The current tooling is already able to export-import metadata-only `.carto` (although it's not exposed in the UI).

Maybe the private repo is a better option, just in case. These basemaps are old (2013) and nobody really knows if they should be made public :D If storing metadata `.carto` + images in GH is fine, we can do it in the private repo (can you link it?). I prefer GH, since it's harder that we accidentally delete them.

**Comment by jaakla** [comment]
ok, I see. git-friendly would be to save the jsons as plain text, so you can see the history and diffs :) Real usage of them later would require specific data files also. If you put them to repo as individual gpkg files, then they seem to fit to github tech limits (100MB); and most of them are shared between different styles, so maybe this makes sense?
